### ISSUE TITLE
Error compiling Makefile in dist/linux on Ubuntu 14.04

### ISSUE THREAD

**Issue by realtable** [lukalafaye/SafeSync#1]
I'm trying to install SafeSync on my Ubuntu distro, but the Makefile contains directories and files that are local to `luka`'s file system. Correct me if I'm wrong, but I can't find any instructions that tell me how to install this correctly. Does anyone know how I can fix this?

```
realtable@computer:~/SafeSync/dist/linux$ make
/home/luka/Qt5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile ../../src/tests.pro -spec linux-g++
make: /home/luka/Qt5.10.1/5.10.1/gcc_64/bin/qmake: Command not found
make: *** [Makefile] Error 127
```

**Comment by realtable** [comment]
@lukalafaye I opened this issue a while ago, and since then found [the SafeSync website](https://lukalafaye.github.io/SafeSync/). When I go to click download however, I get a 404 for [this page](https://github.com/lukalafaye/SafeSync/releases/tag/v1.0.0). I'm led to believe that there may be an executable or something there.

I'd really like to try out your software, but I can't seem to find a way. Can you help me with this?

**Comment by lukalafaye** [comment]
The software is in progress, I'll finish the wiki when I'll have time!

**Comment by aeternesatiatus** [comment]
It should work now: https://github.com/aeternesatiatus/SafeSync/wiki

**Comment by aeternesatiatus** [comment]
It should work now: https://github.com/aeternesatiatus/SafeSync/wiki
@realtable
